# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-N1

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Select Armbian Kernel'
        required: true
        default: '6.1.21'

jobs:

  build_openwrt:

    name: Build OpenWrt Firmware

    runs-on: ubuntu-latest

    steps:
      - name: Space cleanup and Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* moby* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Checkout OpenWrt
        uses: actions/checkout@v3

      - name: Update feeds
        run: |
          sed -i '$a src-git kenzo https://github.com/kenzok8/openwrt-packages' ./feeds.conf.default
          sed -i '$a src-git small https://github.com/kenzok8/small' ./feeds.conf.default
          # sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Install Clash Binaries
        run: |
          cd package/base-files/files
          mkdir -p etc/openclash/core
          wget -qO- https://raw.githubusercontent.com/vernesong/OpenClash/core/master/dev/clash-linux-arm64.tar.gz | tar xOvz > etc/openclash/core/clash
          chmod +x etc/openclash/core/clash*

      - name: Modify network configuration
        run: |
          sed -i 's/lan) ipad=${ipaddr:-"192.168.1.1"} ;;/lan) ipad=${ipaddr:-"192.168.128.254"} ;;/g' ./package/base-files/files/bin/config_generate

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          cat >> .config <<EOF
          CONFIG_TARGET_armvirt=y
          CONFIG_TARGET_armvirt_64=y
          CONFIG_TARGET_armvirt_64_Default=y
          CONFIG_BRCMFMAC_PCIE=y
          CONFIG_BRCMFMAC_SDIO=y
          CONFIG_BRCMFMAC_USB=y
          CONFIG_BTRFS_PROGS_ZSTD=y
          CONFIG_DOCKER_CGROUP_OPTIONS=y
          CONFIG_DOCKER_NET_MACVLAN=y
          CONFIG_DOCKER_STO_EXT4=y
          CONFIG_DRIVER_11AC_SUPPORT=y
          CONFIG_DRIVER_11N_SUPPORT=y
          CONFIG_GNUTLS_ALPN=y
          CONFIG_GNUTLS_ANON=y
          CONFIG_GNUTLS_DTLS_SRTP=y
          CONFIG_GNUTLS_HEARTBEAT=y
          CONFIG_GNUTLS_OCSP=y
          CONFIG_GNUTLS_PSK=y
          CONFIG_KERNEL_CGROUP_DEVICE=y
          CONFIG_KERNEL_CGROUP_FREEZER=y
          CONFIG_KERNEL_CGROUP_NET_PRIO=y
          CONFIG_KERNEL_EXT4_FS_POSIX_ACL=y
          CONFIG_KERNEL_EXT4_FS_SECURITY=y
          CONFIG_KERNEL_FS_POSIX_ACL=y
          CONFIG_KERNEL_NET_CLS_CGROUP=y
          CONFIG_MBEDTLS_AES_C=y
          CONFIG_MBEDTLS_CMAC_C=y
          CONFIG_MBEDTLS_DES_C=y
          CONFIG_MBEDTLS_ECP_DP_CURVE25519_ENABLED=y
          CONFIG_MBEDTLS_ECP_DP_SECP256K1_ENABLED=y
          CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED=y
          CONFIG_MBEDTLS_ECP_DP_SECP384R1_ENABLED=y
          CONFIG_MBEDTLS_ENTROPY_FORCE_SHA256=y
          CONFIG_MBEDTLS_GCM_C=y
          CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED=y
          CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED=y
          CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED=y
          CONFIG_MBEDTLS_KEY_EXCHANGE_PSK_ENABLED=y
          CONFIG_MBEDTLS_NIST_KW_C=y
          CONFIG_MBEDTLS_RSA_NO_CRT=y
          CONFIG_PACKAGE_6in4=y
          CONFIG_PACKAGE_MAC80211_DEBUGFS=y
          CONFIG_PACKAGE_MAC80211_MESH=y
          CONFIG_PACKAGE_TAR_BZIP2=y
          CONFIG_PACKAGE_TAR_GZIP=y
          CONFIG_PACKAGE_TAR_XZ=y
          CONFIG_PACKAGE_TAR_ZSTD=y
          CONFIG_PACKAGE_attr=y
          CONFIG_PACKAGE_avahi-dbus-daemon=y
          CONFIG_PACKAGE_bash=y
          CONFIG_PACKAGE_blkid=y
          CONFIG_PACKAGE_boost=y
          CONFIG_PACKAGE_boost-date_time=y
          CONFIG_PACKAGE_boost-program_options=y
          CONFIG_PACKAGE_boost-system=y
          CONFIG_PACKAGE_brcmfmac-firmware-usb=y
          CONFIG_PACKAGE_bsdtar=y
          CONFIG_PACKAGE_btrfs-progs=y
          CONFIG_PACKAGE_bzip2=y
          CONFIG_PACKAGE_cgroupfs-mount=y
          CONFIG_PACKAGE_chattr=y
          CONFIG_PACKAGE_containerd=y
          CONFIG_PACKAGE_coreutils-nohup=y
          CONFIG_PACKAGE_dbus=y
          CONFIG_PACKAGE_docker=y
          CONFIG_PACKAGE_dockerd=y
          CONFIG_PACKAGE_dosfstools=y
          # CONFIG_PACKAGE_etherwake is not set
          CONFIG_PACKAGE_f2fs-tools=y
          CONFIG_PACKAGE_f2fsck=y
          CONFIG_PACKAGE_fdisk=y
          CONFIG_PACKAGE_gawk=y
          CONFIG_PACKAGE_getopt=y
          CONFIG_PACKAGE_hostapd-common=y
          CONFIG_PACKAGE_hysteria=y
          CONFIG_PACKAGE_ip6tables=y
          CONFIG_PACKAGE_ip6tables-extra=y
          CONFIG_PACKAGE_ip6tables-mod-nat=y
          CONFIG_PACKAGE_ipt2socks=y
          CONFIG_PACKAGE_iputils-arping=y
          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_iw=y
          CONFIG_PACKAGE_iwinfo=y
          CONFIG_PACKAGE_jq=y
          CONFIG_PACKAGE_kmod-br-netfilter=y
          CONFIG_PACKAGE_kmod-brcmfmac=y
          CONFIG_PACKAGE_kmod-brcmutil=y
          CONFIG_PACKAGE_kmod-cfg80211=y
          CONFIG_PACKAGE_kmod-crypto-cbc=y
          CONFIG_PACKAGE_kmod-crypto-ccm=y
          CONFIG_PACKAGE_kmod-crypto-cmac=y
          CONFIG_PACKAGE_kmod-crypto-crc32c=y
          CONFIG_PACKAGE_kmod-crypto-ctr=y
          CONFIG_PACKAGE_kmod-crypto-des=y
          CONFIG_PACKAGE_kmod-crypto-gcm=y
          CONFIG_PACKAGE_kmod-crypto-gf128=y
          CONFIG_PACKAGE_kmod-crypto-ghash=y
          CONFIG_PACKAGE_kmod-crypto-hmac=y
          CONFIG_PACKAGE_kmod-crypto-md4=y
          CONFIG_PACKAGE_kmod-crypto-md5=y
          CONFIG_PACKAGE_kmod-crypto-rng=y
          CONFIG_PACKAGE_kmod-crypto-seqiv=y
          CONFIG_PACKAGE_kmod-crypto-sha256=y
          CONFIG_PACKAGE_kmod-crypto-sha512=y
          CONFIG_PACKAGE_kmod-dax=y
          CONFIG_PACKAGE_kmod-dm=y
          CONFIG_PACKAGE_kmod-dummy=y
          CONFIG_PACKAGE_kmod-fs-btrfs=y
          CONFIG_PACKAGE_kmod-fs-cifs=y
          CONFIG_PACKAGE_kmod-ikconfig=y
          CONFIG_PACKAGE_kmod-inet-diag=y
          CONFIG_PACKAGE_kmod-ip6tables=y
          CONFIG_PACKAGE_kmod-ip6tables-extra=y
          CONFIG_PACKAGE_kmod-ipt-nat6=y
          CONFIG_PACKAGE_kmod-iptunnel=y
          CONFIG_PACKAGE_kmod-iptunnel4=y
          CONFIG_PACKAGE_kmod-keys-encrypted=y
          CONFIG_PACKAGE_kmod-keys-trusted=y
          CONFIG_PACKAGE_kmod-lib-crc32c=y
          CONFIG_PACKAGE_kmod-lib-raid6=y
          CONFIG_PACKAGE_kmod-lib-xor=y
          CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
          CONFIG_PACKAGE_kmod-lib-zlib-inflate=y
          CONFIG_PACKAGE_kmod-lib-zstd=y
          CONFIG_PACKAGE_kmod-mac80211=y
          CONFIG_PACKAGE_kmod-mii=y
          CONFIG_PACKAGE_kmod-mmc=y
          CONFIG_PACKAGE_kmod-nf-ipt6=y
          CONFIG_PACKAGE_kmod-nf-ipvs=y
          CONFIG_PACKAGE_kmod-nf-log6=y
          CONFIG_PACKAGE_kmod-nf-nat6=y
          CONFIG_PACKAGE_kmod-nf-reject6=y
          CONFIG_PACKAGE_kmod-nls-base=y
          CONFIG_PACKAGE_kmod-nls-utf8=y
          CONFIG_PACKAGE_kmod-qmi_wwan_q=y
          CONFIG_PACKAGE_kmod-random-core=y
          CONFIG_PACKAGE_kmod-sit=y
          CONFIG_PACKAGE_kmod-tpm=y
          CONFIG_PACKAGE_kmod-usb-acm=y
          CONFIG_PACKAGE_kmod-usb-core=y
          CONFIG_PACKAGE_kmod-usb-ehci=y
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-mbim=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-ncm=y
          CONFIG_PACKAGE_kmod-usb-net-qmi-wwan=y
          CONFIG_PACKAGE_kmod-usb-net-rndis=y
          CONFIG_PACKAGE_kmod-usb-net-sierrawireless=y
          CONFIG_PACKAGE_kmod-usb-ohci=y
          CONFIG_PACKAGE_kmod-usb-serial=y
          CONFIG_PACKAGE_kmod-usb-serial-option=y
          CONFIG_PACKAGE_kmod-usb-serial-qualcomm=y
          CONFIG_PACKAGE_kmod-usb-serial-wwan=y
          CONFIG_PACKAGE_kmod-usb-wdm=y
          CONFIG_PACKAGE_kmod-usb-xhci-hcd=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb3=y
          CONFIG_PACKAGE_kmod-veth=y
          CONFIG_PACKAGE_libarchive=y
          CONFIG_PACKAGE_libatomic=y
          CONFIG_PACKAGE_libattr=y
          CONFIG_PACKAGE_libavahi-client=y
          CONFIG_PACKAGE_libavahi-dbus-support=y
          CONFIG_PACKAGE_libbz2=y
          CONFIG_PACKAGE_libcap=y
          CONFIG_PACKAGE_libcap-bin=y
          CONFIG_PACKAGE_libcap-bin-capsh-shell="/bin/sh"
          CONFIG_PACKAGE_libdaemon=y
          CONFIG_PACKAGE_libdbus=y
          CONFIG_PACKAGE_libdevmapper=y
          CONFIG_PACKAGE_libexpat=y
          CONFIG_PACKAGE_libfdisk=y
          CONFIG_PACKAGE_libgmp=y
          CONFIG_PACKAGE_libgnutls=y
          CONFIG_PACKAGE_liblzma=y
          CONFIG_PACKAGE_liblzo=y
          CONFIG_PACKAGE_libmaxminddb=y
          CONFIG_PACKAGE_libmbedtls=y
          CONFIG_PACKAGE_libminiupnpc=y
          CONFIG_PACKAGE_libmount=y
          CONFIG_PACKAGE_libnatpmp=y
          CONFIG_PACKAGE_libncurses=y
          CONFIG_PACKAGE_libnettle=y
          CONFIG_PACKAGE_libnetwork=y
          CONFIG_PACKAGE_libparted=y
          CONFIG_PACKAGE_libpopt=y
          CONFIG_PACKAGE_libreadline=y
          CONFIG_PACKAGE_libruby=y
          CONFIG_PACKAGE_libseccomp=y
          CONFIG_PACKAGE_libsmartcols=y
          CONFIG_PACKAGE_libstdcpp=y
          CONFIG_PACKAGE_libtasn1=y
          CONFIG_PACKAGE_libtirpc=y
          CONFIG_PACKAGE_liburing=y
          CONFIG_PACKAGE_libuv=y
          CONFIG_PACKAGE_libwebsockets-full=y
          CONFIG_PACKAGE_libyaml=y
          CONFIG_PACKAGE_libzstd=y
          CONFIG_PACKAGE_losetup=y
          CONFIG_PACKAGE_lsattr=y
          CONFIG_PACKAGE_lsblk=y
          CONFIG_PACKAGE_lua-cjson=y
          CONFIG_PACKAGE_lua-maxminddb=y
          CONFIG_PACKAGE_luasocket=y
          # CONFIG_PACKAGE_luci-app-accesscontrol is not set
          CONFIG_PACKAGE_luci-app-amlogic=y
          CONFIG_PACKAGE_luci-app-argonne-config=y
          CONFIG_PACKAGE_luci-app-cifs-mount=y
          CONFIG_PACKAGE_luci-app-diskman=y
          CONFIG_PACKAGE_luci-app-dockerman=y
          CONFIG_PACKAGE_luci-app-openclash=y
          CONFIG_PACKAGE_luci-app-pushbot=y
          CONFIG_PACKAGE_luci-app-samba4=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-usbmodem=y
          CONFIG_PACKAGE_luci-app-uugamebooster=y
          CONFIG_PACKAGE_luci-app-v2ray-server=y
          CONFIG_PACKAGE_luci-app-vssr=y
          # CONFIG_PACKAGE_luci-app-wol is not set
          CONFIG_PACKAGE_luci-app-zerotier=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_luci-i18n-amlogic-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-argonne-config-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-cifs-mount-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-diskman-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-dockerman-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-samba4-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-usbmodem-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-uugamebooster-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-v2ray-server-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-vssr-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-zerotier-zh-cn=y
          CONFIG_PACKAGE_luci-lib-docker=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          CONFIG_PACKAGE_luci-theme-argonne=y
          CONFIG_PACKAGE_mount-utils=y
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
          CONFIG_PACKAGE_odhcpd-ipv6only=y
          CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
          CONFIG_PACKAGE_parted=y
          CONFIG_PACKAGE_perl=y
          CONFIG_PACKAGE_perl-http-date=y
          CONFIG_PACKAGE_perlbase-base=y
          CONFIG_PACKAGE_perlbase-bytes=y
          CONFIG_PACKAGE_perlbase-charnames=y
          CONFIG_PACKAGE_perlbase-class=y
          CONFIG_PACKAGE_perlbase-config=y
          CONFIG_PACKAGE_perlbase-cwd=y
          CONFIG_PACKAGE_perlbase-dynaloader=y
          CONFIG_PACKAGE_perlbase-errno=y
          CONFIG_PACKAGE_perlbase-essential=y
          CONFIG_PACKAGE_perlbase-fcntl=y
          CONFIG_PACKAGE_perlbase-file=y
          CONFIG_PACKAGE_perlbase-filehandle=y
          CONFIG_PACKAGE_perlbase-getopt=y
          CONFIG_PACKAGE_perlbase-i18n=y
          CONFIG_PACKAGE_perlbase-integer=y
          CONFIG_PACKAGE_perlbase-io=y
          CONFIG_PACKAGE_perlbase-list=y
          CONFIG_PACKAGE_perlbase-locale=y
          CONFIG_PACKAGE_perlbase-params=y
          CONFIG_PACKAGE_perlbase-posix=y
          CONFIG_PACKAGE_perlbase-re=y
          CONFIG_PACKAGE_perlbase-scalar=y
          CONFIG_PACKAGE_perlbase-selectsaver=y
          CONFIG_PACKAGE_perlbase-socket=y
          CONFIG_PACKAGE_perlbase-symbol=y
          CONFIG_PACKAGE_perlbase-tie=y
          CONFIG_PACKAGE_perlbase-time=y
          CONFIG_PACKAGE_perlbase-unicode=y
          CONFIG_PACKAGE_perlbase-unicore=y
          CONFIG_PACKAGE_perlbase-utf8=y
          CONFIG_PACKAGE_perlbase-xsloader=y
          CONFIG_PACKAGE_pigz=y
          CONFIG_PACKAGE_pv=y
          CONFIG_PACKAGE_quectel-CM-5G=y
          CONFIG_PACKAGE_ruby=y
          CONFIG_PACKAGE_ruby-bigdecimal=y
          CONFIG_PACKAGE_ruby-date=y
          CONFIG_PACKAGE_ruby-digest=y
          CONFIG_PACKAGE_ruby-enc=y
          CONFIG_PACKAGE_ruby-forwardable=y
          CONFIG_PACKAGE_ruby-pstore=y
          CONFIG_PACKAGE_ruby-psych=y
          CONFIG_PACKAGE_ruby-stringio=y
          CONFIG_PACKAGE_ruby-strscan=y
          CONFIG_PACKAGE_ruby-yaml=y
          CONFIG_PACKAGE_runc=y
          CONFIG_PACKAGE_samba4-libs=y
          CONFIG_PACKAGE_samba4-server=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-local=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-redir=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-server=y
          CONFIG_PACKAGE_smartmontools=y
          CONFIG_PACKAGE_tar=y
          CONFIG_PACKAGE_terminfo=y
          CONFIG_PACKAGE_tini=y
          CONFIG_PACKAGE_trojan=y
          CONFIG_PACKAGE_ttyd=y
          CONFIG_PACKAGE_unzip=y
          CONFIG_PACKAGE_uugamebooster=y
          CONFIG_PACKAGE_uuidgen=y
          CONFIG_PACKAGE_wireless-regdb=y
          # CONFIG_PACKAGE_wol is not set
          CONFIG_PACKAGE_wpa-cli=y
          CONFIG_PACKAGE_wpad-basic=y
          CONFIG_PACKAGE_wsdd2=y
          CONFIG_PACKAGE_xfs-fsck=y
          CONFIG_PACKAGE_xfs-mkfs=y
          CONFIG_PACKAGE_xray-plugin=y
          CONFIG_PACKAGE_xz=y
          CONFIG_PACKAGE_xz-utils=y
          CONFIG_PACKAGE_zerotier=y
          CONFIG_PARTED_READLINE=y
          CONFIG_PERL_NOCOMMENT=y
          CONFIG_PERL_THREADS=y
          CONFIG_SAMBA4_SERVER_AVAHI=y
          CONFIG_SAMBA4_SERVER_NETBIOS=y
          CONFIG_SAMBA4_SERVER_VFS=y
          CONFIG_SAMBA4_SERVER_WSDD2=y
          # CONFIG_TARGET_IMAGES_GZIP is not set
          # CONFIG_TARGET_ROOTFS_CPIOGZ is not set
          # CONFIG_TARGET_ROOTFS_EXT4FS is not set
          # CONFIG_TARGET_ROOTFS_INITRAMFS is not set
          # CONFIG_TARGET_ROOTFS_SQUASHFS is not set
          CONFIG_WPA_MSG_MIN_PRIORITY=3
          CONFIG_ZSTD_OPTIMIZE_O3=y
          CONFIG_boost-compile-visibility-hidden=y
          CONFIG_boost-runtime-shared=y
          CONFIG_boost-static-and-shared-libs=y
          CONFIG_boost-variant-release=y
          EOF

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Download packages
        run: make download -j16

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Package Armvirt as OpenWrt
        uses: unifreq/openwrt_packit@master
        env:
          OPENWRT_ARMVIRT: ./bin/targets/armvirt/64/openwrt-armvirt-64-default-rootfs.tar.gz
          PACKAGE_SOC: s905d
          KERNEL_VERSION_NAME: ${{ inputs.kernel_version }}
          SAVE_OPENWRT_ARMVIRT: false
          WHOAMI: harry

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Upload buildinfo
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Upload rootfs
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_rootfs
          path: ./bin/targets/armvirt/64/openwrt-armvirt-64-default-rootfs.tar.gz
  
      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_firmware
          path: ${{ env.PACKAGED_OUTPUTPATH }}/

      - name: Upload firmware to Release
        uses: ncipollo/release-action@main
        with:
          tag: openwrt_armvirt_v8_${{ env.PACKAGED_OUTPUTDATE }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is OpenWrt firmware for Armvirt 64
            * Firmware information
            Default IP: 192.168.128.254
            Default username: root
            Default password: password
